package render

import (
	"fmt"
	"net"
	"strings"

	"firewall/ui/internal/config"
)

// NetworkService is the rc.d service name and path for the generated interface
// setup script.
const (
	NetworkService = "fwnetwork"
	NetworkRcPath  = "/usr/local/etc/rc.d/" + NetworkService
)

// Network renders the rc.d script that puts the configured addressing and NIC
// tuning onto the physical interfaces.
//
// Interface addressing is config the engine claims to own, and until this
// existed nothing applied it: pf's `$lan_if:network` macros resolve against the
// live interface, so on a stock install the very first apply could not even
// validate, and an address changed in the UI was rendered into unbound and Kea
// for an address the NIC did not have (docs/design-review.md §3.1). The test VM
// only worked because provisioning aliased the address by hand.
//
// It is a script rather than an rc.conf fragment for the same reason pflow is
// (render.Pflow): the work is imperative, it must be replayable at apply time
// so a UI edit takes effect without a reboot, and it must be idempotent so
// repeated applies are free. Every block is guarded — a configured device that
// is not present on this box warns and is skipped instead of failing the
// apply, which is what lets one image boot on boards with different port
// counts.
//
// Addresses are only touched when they differ from what the interface already
// carries, so an apply that changes an unrelated setting never drops the
// admin's own LAN session.
func Network(cfg config.Config) (string, error) {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("#!/bin/sh")
	w("# Generated by fwd — do not edit; changes are overwritten on apply.")
	w("# Interface addressing and NIC tuning for the appliance's own ports.")
	w("#")
	w("# PROVIDE: %s", NetworkService)
	w("# REQUIRE: FILESYSTEMS netif")
	w("# BEFORE: pf")
	w("# KEYWORD: nojail")
	w("")
	w(". /etc/rc.subr")
	w("")
	w("name=%s", NetworkService)
	w("rcvar=%s_enable", NetworkService)
	w("start_cmd=%s_start", NetworkService)
	w("stop_cmd=\":\"") // tearing down the network on shutdown helps nobody
	w("")
	w("load_rc_config $name")
	w(": ${%s_enable:=\"NO\"}", NetworkService)
	w("")

	// Shared helper: everything below runs per device and must tolerate a
	// device that does not exist on this particular board.
	w("%s_have() {", NetworkService)
	w("\tifconfig \"$1\" >/dev/null 2>&1")
	w("}")
	w("")

	w("%s_start() {", NetworkService)
	for _, ifc := range cfg.Interfaces {
		if err := writeInterface(w, ifc); err != nil {
			return "", err
		}
	}
	w("}")
	w("")
	w("run_rc_command \"$1\"")

	return b.String(), nil
}

// writeInterface emits the setup block for one interface.
func writeInterface(w func(string, ...any), ifc config.Interface) error {
	dev := ifc.Device
	// Every interpolation of an operator-settable value below is shell-quoted;
	// config.validateShellSafe has already constrained dev and Gateway to
	// grammars with no shell metacharacters (docs/security-plan.md SEC-1).
	q := shellQuote(dev)
	w("\t# %s (%s)", ifc.Name, ifc.Role)
	w("\tif %s_have %s; then", NetworkService, q)

	// Link-level tuning first, so it is in force before any address or
	// traffic lands on the port. Unsupported capabilities are not an error:
	// ifconfig rejects a flag the driver lacks and we carry on.
	flags := "-tso -lro -txcsum -rxcsum -txcsum6 -rxcsum6"
	why := "offloads off: wrong for a forwarding path, and they hand the flow classifier merged frames"
	if ifc.HardwareOffload {
		flags = "tso lro txcsum rxcsum txcsum6 rxcsum6"
		why = "offloads explicitly re-enabled in config"
	}
	w("\t\t# %s", why)
	w("\t\tifconfig %s %s >/dev/null 2>&1 || true", q, flags)

	// Energy Efficient Ethernet is a link-stability liability on i225/i226
	// and buys nothing on a mains-powered appliance. igc(4) defaults it off;
	// pin it so a driver default change cannot quietly turn it back on.
	if driver, unit, ok := splitDevice(dev); ok {
		w("\t\tsysctl %s >/dev/null 2>&1 || true",
			shellQuote(fmt.Sprintf("dev.%s.%s.eee_control=0", driver, unit)))
	}

	if ifc.MTU > 0 {
		w("\t\tifconfig %s mtu %d >/dev/null 2>&1 || true", q, ifc.MTU)
	}

	switch {
	case ifc.IPv4 != "":
		ip, ipnet, err := net.ParseCIDR(ifc.IPv4)
		if err != nil {
			return fmt.Errorf("network: %s address: %w", ifc.Name, err)
		}
		ones, _ := ipnet.Mask.Size()
		// FreeBSD prints the mask in hex; matching address *and* mask means a
		// changed prefix length is noticed, not just a changed address.
		w("\t\t# Only re-address when it differs, so an unrelated apply does not")
		w("\t\t# drop established sessions on this port.")
		w("\t\tif ! ifconfig %s inet 2>/dev/null | grep -q 'inet %s netmask %s'; then",
			q, ip.String(), hexMask(ipnet.Mask))
		w("\t\t\tfor a in $(ifconfig %s inet 2>/dev/null | awk '/^\\tinet /{print $2}'); do", q)
		w("\t\t\t\tifconfig %s inet \"$a\" -alias >/dev/null 2>&1 || true", q)
		w("\t\t\tdone")
		w("\t\t\tifconfig %s inet %s/%d alias", q, ip.String(), ones)
		w("\t\tfi")
	case ifc.DHCPClient:
		w("\t\t# Lease-driven: only kick dhclient when the port has no address,")
		w("\t\t# so a running lease is left alone across applies.")
		w("\t\tif ! ifconfig %s inet 2>/dev/null | grep -q 'inet '; then", q)
		w("\t\t\tservice dhclient onestart %s >/dev/null 2>&1 || true", q)
		w("\t\tfi")
	}

	w("\t\tifconfig %s up", q)

	if ifc.Gateway != "" {
		w("\t\t# Default route via the configured next hop.")
		w("\t\tcur=$(route -n get default 2>/dev/null | awk '/gateway:/{print $2}')")
		w("\t\tif [ \"$cur\" != %s ]; then", shellQuote(ifc.Gateway))
		w("\t\t\troute -q delete default >/dev/null 2>&1 || true")
		w("\t\t\troute -q add default %s >/dev/null 2>&1 || true", shellQuote(ifc.Gateway))
		w("\t\tfi")
	}

	w("\telse")
	w("\t\techo %s >&2", shellQuote(fmt.Sprintf(
		"%s: device %s is not present on this system; skipped", NetworkService, dev)))
	w("\tfi")
	w("")
	return nil
}

// splitDevice splits a FreeBSD device name into its driver and unit ("igc0" ->
// "igc", "0"), which is how the sysctl tree is keyed. Returns ok=false for a
// name that is not driver+unit.
func splitDevice(dev string) (driver, unit string, ok bool) {
	i := len(dev)
	for i > 0 && dev[i-1] >= '0' && dev[i-1] <= '9' {
		i--
	}
	if i == 0 || i == len(dev) {
		return "", "", false
	}
	return dev[:i], dev[i:], true
}

// hexMask formats a netmask the way FreeBSD's ifconfig prints it (0xffffff00).
func hexMask(m net.IPMask) string {
	if len(m) != net.IPv4len {
		if v4 := net.IP(m).To4(); v4 != nil {
			m = net.IPMask(v4)
		}
	}
	var v uint32
	for _, b := range m {
		v = v<<8 | uint32(b)
	}
	return fmt.Sprintf("0x%08x", v)
}
