package render

import (
	"fmt"
	"net"
	"strings"

	"firewall/ui/internal/config"
)

const (
	// NtopngDataDir holds ntopng's runtime state (Redis-less community mode
	// keeps its timeseries and host cache here).
	NtopngDataDir = "/var/db/ntopng"
	// NtopngHTTPPrefix is the URL base ntopng generates links under. It must
	// match the path the WebUI reverse-proxies ntopng at (server package), so
	// every link ntopng emits routes back through the appliance session gate.
	NtopngHTTPPrefix = "/visibility/app"
)

// Ntopng renders ntopng.conf (plan.md §8): deep traffic visibility with nDPI
// app-layer identification on the appliance's own interfaces. ntopng captures
// north-south and inter-segment traffic directly (no extra hardware) and runs
// nDPI automatically on what it sees.
//
// The web UI binds to localhost only and login is disabled here on purpose:
// fwd reverse-proxies ntopng under NtopngHTTPPrefix behind the WebUI session,
// so the appliance auth is the single front door — exposing ntopng's own login
// would be a second, weaker credential store.
//
// When Visibility is disabled the file is rendered comment-only; apply pairs it
// with `service ntopng stop` so nothing captures.
func Ntopng(cfg config.Config) (string, error) {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# Generated by fwd — do not edit; changes are overwritten on apply.")
	if !cfg.Visibility.Enabled {
		w("# Network visibility is disabled.")
		return b.String(), nil
	}

	// Resolve monitored interface names to capture devices.
	device := map[string]string{}
	for _, ifc := range cfg.Interfaces {
		device[ifc.Name] = ifc.Device
	}
	var devices []string
	for _, name := range cfg.Visibility.Monitored(&cfg) {
		dev, ok := device[name]
		if !ok {
			return "", fmt.Errorf("ntopng: unknown interface %q", name)
		}
		if dev == "" {
			return "", fmt.Errorf("ntopng: interface %q has no device", name)
		}
		devices = append(devices, dev)
	}
	if len(devices) == 0 {
		return "", fmt.Errorf("ntopng: no interface to monitor")
	}

	// Local networks: the internal (non-WAN) subnets, so ntopng classifies
	// hosts as local vs remote correctly for east-west accounting.
	var locals []string
	for _, ifc := range cfg.Interfaces {
		if ifc.Role == "wan" || ifc.IPv4 == "" {
			continue
		}
		_, ipnet, err := net.ParseCIDR(ifc.IPv4)
		if err != nil {
			return "", fmt.Errorf("ntopng: %s address: %w", ifc.Name, err)
		}
		locals = append(locals, ipnet.String())
	}

	w("--community")
	w("--data-dir=%s", NtopngDataDir)
	w("--http-port=127.0.0.1:%d", cfg.Visibility.Port())
	w("--http-prefix=%s", NtopngHTTPPrefix)
	// Localhost-only behind the WebUI proxy; the appliance session is the gate.
	w("--disable-login=1")
	if len(locals) > 0 {
		w("--local-networks=%s", strings.Join(locals, ","))
	}
	for _, dev := range devices {
		w("-i=%s", dev)
	}

	return b.String(), nil
}
