package render

import (
	"fmt"
	"strings"

	"firewall/ui/internal/config"
)

// NTPConfPath is the appliance's ntpd configuration.
const NTPConfPath = "/etc/ntp.conf"

// NTP renders ntp.conf for the base-system ntpd.
//
// System.NTPServers was previously accepted by the UI, stored, and rendered
// nowhere — the admin configured time sources and nothing used them
// (docs/design-review.md §3.4).
//
// The restrict lines are the standard closed-by-default posture: the appliance
// is a client, not a public time server, so it takes no queries from the
// network. Time still matters here beyond tidiness — TLS certificate validation
// (the WebUI's own cert, DNS-over-TLS upstreams) fails in confusing ways when
// the clock is far off, which on a box with no RTC battery is the state it
// boots in.
func NTP(cfg config.Config) (string, error) {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# Generated by fwd — do not edit; changes are overwritten on apply.")
	w("driftfile /var/db/ntpd.drift")
	w("")
	w("# Client only: answer nothing from the network.")
	w("restrict default limited kod nomodify notrap noquery nopeer")
	w("restrict source limited kod nomodify notrap noquery")
	w("restrict 127.0.0.1")
	w("restrict ::1")
	w("")
	if len(cfg.System.NTPServers) == 0 {
		w("# No time sources configured; ntpd is stopped.")
		return b.String(), nil
	}
	for _, s := range cfg.System.NTPServers {
		// iburst: get to a usable clock in seconds rather than minutes, which
		// matters on an appliance that may have booted with a wrong date.
		w("server %s iburst", s)
	}
	return b.String(), nil
}
