// Package render turns the declarative config into service configuration
// files. Renderers are pure functions over config.Config so they can be
// golden-file tested without a FreeBSD host; applying the output (pfctl -nf,
// service reloads, confirm-or-rollback) is config.Apply's job.
package render

import (
	"fmt"
	"strings"

	"firewall/ui/internal/config"
)

// PF renders a complete pf.conf for FreeBSD pf: default-deny inbound on WAN,
// open LAN, automatic outbound NAT, and rdr+pass pairs for port forwards.
func PF(cfg config.Config) (string, error) {
	wan, ok := byRole(cfg, "wan")
	if !ok {
		return "", fmt.Errorf("pf: no wan interface")
	}

	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# Generated by fwd — do not edit; changes are overwritten on apply.")
	w("# Source of truth: the appliance config (plan.md §7).")
	w("")

	// Macros, one per interface role.
	for _, ifc := range cfg.Interfaces {
		w("%s = \"%s\"", macro(ifc), ifc.Device)
	}
	w("")

	w("set skip on lo0")
	w("set block-policy drop")
	w("set loginterface $%s", macro(wan))
	w("")
	w("scrub in all fragment reassemble")
	w("")

	// Outbound NAT. ($wan_if) keeps working when the WAN address changes
	// under DHCP without a reload.
	w("# Outbound NAT")
	switch cfg.NAT.OutboundMode {
	case "automatic":
		for _, ifc := range cfg.Interfaces {
			if ifc.Role == "wan" || ifc.IPv4 == "" {
				continue
			}
			w("nat on $%s inet from $%s:network to any -> ($%s)", macro(wan), macro(ifc), macro(wan))
		}
	default:
		w("# TODO: manual outbound NAT rules")
	}
	w("")

	enabled := enabledForwards(cfg)

	w("# Port forwards (rdr)")
	for _, pf := range enabled {
		w("rdr on $%s inet proto %s from any to ($%s) port %d -> %s port %d # %s",
			macro(wan), proto(pf.Proto), macro(wan), pf.WANPort, pf.DestIP, pf.DestPort, pf.Name)
	}
	w("")

	w("# Filter: default deny in, allow out from the firewall itself")
	w("block in log all")
	w("pass out quick inet keep state")
	w("antispoof quick for $%s", macro(wan))
	w("")

	w("# LAN and OPT networks are trusted")
	for _, ifc := range cfg.Interfaces {
		if ifc.Role == "wan" || (ifc.IPv4 == "" && !ifc.DHCPClient) {
			continue
		}
		w("pass in on $%s inet all keep state", macro(ifc))
	}
	w("")

	if len(enabled) > 0 {
		w("# Port forwards (pass redirected traffic)")
		for _, pf := range enabled {
			w("pass in on $%s inet proto %s from any to %s port %d keep state # %s",
				macro(wan), proto(pf.Proto), pf.DestIP, pf.DestPort, pf.Name)
		}
		w("")
	}

	if ports := wgListenPorts(cfg); len(ports) > 0 {
		w("# WireGuard")
		for _, port := range ports {
			w("pass in on $%s inet proto udp from any to ($%s) port %d keep state", macro(wan), macro(wan), port)
		}
		// TODO: pass rules on the wg tunnel interfaces once tunnel
		// device naming is wired up in config.
		w("")
	}

	wgServerRules(&b, cfg, wan)

	return b.String(), nil
}

// wgServerRules emits the remote-access server's pf rules: open its UDP listen
// port on the wan, then default-deny on the VPN interface with one explicit
// pass per client/service grant. Default deny means a client with no grants
// reaches nothing on the network.
func wgServerRules(b *strings.Builder, cfg config.Config, wan config.Interface) {
	s := cfg.WireGuard.Server
	if !cfg.WireGuard.Enabled || !s.Enabled {
		return
	}
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }

	w("# WireGuard remote-access server")
	w("pass in on $%s inet proto udp from any to ($%s) port %d keep state", macro(wan), macro(wan), s.Port())
	// Default deny on the VPN interface; every grant below is an explicit allow.
	w("block in on %s all", WGServerDevice)
	for _, c := range s.Clients {
		clientIP := strings.SplitN(c.Address, "/", 2)[0]
		for _, id := range c.ServiceIDs {
			svc, ok := s.Service(id)
			if !ok {
				continue
			}
			w("pass in on %s inet proto %s from %s to %s port %d keep state # %s -> %s",
				WGServerDevice, proto(svc.Proto), clientIP, svc.IP, svc.Port, c.Email, svc.Name)
		}
	}
	w("")
}

func byRole(cfg config.Config, role string) (config.Interface, bool) {
	for _, ifc := range cfg.Interfaces {
		if ifc.Role == role {
			return ifc, true
		}
	}
	return config.Interface{}, false
}

// macro derives the pf macro name from the interface name: WAN -> wan_if.
func macro(ifc config.Interface) string {
	name := strings.ToLower(ifc.Name)
	var b strings.Builder
	for _, r := range name {
		if r >= 'a' && r <= 'z' || r >= '0' && r <= '9' {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	return b.String() + "_if"
}

// proto maps the config proto to pf syntax; tcp/udp becomes a list.
func proto(p string) string {
	if p == "tcp/udp" {
		return "{ tcp udp }"
	}
	return p
}

func enabledForwards(cfg config.Config) []config.PortForward {
	var out []config.PortForward
	for _, pf := range cfg.NAT.PortForwards {
		if pf.Enabled {
			out = append(out, pf)
		}
	}
	return out
}

// wgListenPorts returns the listen ports of enabled WireGuard tunnels,
// deduplicated, in tunnel order.
func wgListenPorts(cfg config.Config) []int {
	if !cfg.WireGuard.Enabled {
		return nil
	}
	seen := map[int]bool{}
	var out []int
	for _, t := range cfg.WireGuard.Tunnels {
		if t.ListenPort > 0 && !seen[t.ListenPort] {
			seen[t.ListenPort] = true
			out = append(out, t.ListenPort)
		}
	}
	return out
}
