// Package render turns the declarative config into service configuration
// files. Renderers are pure functions over config.Config so they can be
// golden-file tested without a FreeBSD host; applying the output (pfctl -nf,
// service reloads, confirm-or-rollback) is config.Apply's job.
package render

import (
	"fmt"
	"strconv"
	"strings"

	"firewall/ui/internal/config"
)

// PF renders a complete pf.conf for FreeBSD pf: default-deny inbound on WAN,
// open LAN, automatic outbound NAT, and rdr+pass pairs for port forwards.
func PF(cfg config.Config) (string, error) {
	wan, ok := byRole(cfg, "wan")
	if !ok {
		return "", fmt.Errorf("pf: no wan interface")
	}

	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	// keepState is the state clause appended to pass rules. With baseline
	// visibility on, each rule's states are flagged for pflow(4) export
	// (docs/visibility-design.md §8) so the kernel ships them to the flow
	// collector. A per-rule "(pflow)" is required, not "set state-defaults
	// pflow": an explicit "keep state" on a rule suppresses the global default,
	// and every rule below writes one.
	keepState := "keep state"
	if cfg.Flow.Enabled {
		keepState = "keep state (pflow)"
	}

	w("# Generated by fwd — do not edit; changes are overwritten on apply.")
	w("# Source of truth: the appliance config (plan.md §7).")
	w("")

	// Macros, one per interface role.
	for _, ifc := range cfg.Interfaces {
		w("%s = \"%s\"", macro(ifc), ifc.Device)
	}
	w("")

	w("set skip on lo0")
	w("set block-policy drop")
	w("set loginterface $%s", macro(wan))
	w("")
	w("scrub in all fragment reassemble")
	w("")

	// Outbound NAT. ($wan_if) keeps working when the WAN address changes
	// under DHCP without a reload.
	w("# Outbound NAT")
	switch cfg.NAT.OutboundMode {
	case "automatic":
		for _, ifc := range cfg.Interfaces {
			if ifc.Role == "wan" || ifc.IPv4 == "" {
				continue
			}
			w("nat on $%s inet from $%s:network to any -> ($%s)", macro(wan), macro(ifc), macro(wan))
		}
	default:
		w("# TODO: manual outbound NAT rules")
	}
	w("")

	enabled := enabledForwards(cfg)

	w("# Port forwards (rdr)")
	for _, pf := range enabled {
		w("rdr on $%s inet proto %s from any to ($%s) port %d -> %s port %d # %s",
			macro(wan), proto(pf.Proto), macro(wan), pf.WANPort, pf.DestIP, pf.DestPort, pf.Name)
	}
	w("")

	w("# Filter: default deny in, allow out from the firewall itself")
	w("block in log all")
	w("pass out quick inet %s", keepState)
	w("antispoof quick for $%s", macro(wan))
	w("")

	// Admin plane and per-segment trust (docs/security-plan.md SEC-5).
	//
	// This block used to be one line per interface — "LAN and OPT networks are
	// trusted", pass everything — which meant two things worth separating. It
	// meant every device on the LAN could reach the WebUI and sshd, which is a
	// large surface for a service one person uses. And it meant OPT, the
	// natural home for a guest or IoT segment, had full access to the LAN and
	// to the firewall itself, which is the opposite of why anyone separates a
	// segment.
	writeManagementRules(&b, cfg, keepState)
	writeSegmentRules(&b, cfg, keepState)

	if len(enabled) > 0 {
		w("# Port forwards (pass redirected traffic)")
		for _, pf := range enabled {
			w("pass in on $%s inet proto %s from any to %s port %d %s # %s",
				macro(wan), proto(pf.Proto), pf.DestIP, pf.DestPort, keepState, pf.Name)
		}
		w("")
	}

	if ports := wgListenPorts(cfg); len(ports) > 0 {
		w("# WireGuard site-to-site")
		for _, port := range ports {
			w("pass in on $%s inet proto udp from any to ($%s) port %d %s", macro(wan), macro(wan), port, keepState)
		}
		// The pinhole above only admits the encrypted transport. Decapsulated
		// packets surface on the tunnel interface and are matched again by
		// "block in log all", so without these the tunnel comes up, handshakes,
		// and silently drops every packet through it. Site-to-site links are
		// admin-configured trusted paths — the same trust the LAN and OPT
		// interfaces get above — unlike the remote-access server below, which
		// stays default-deny per client.
		for _, dev := range wgTunnelDevices(cfg) {
			w("pass in on %s inet all %s", dev, keepState)
		}
		w("")
	}

	wgServerRules(&b, cfg, wan)

	return b.String(), nil
}

// wgServerRules emits the remote-access server's pf rules: open its UDP listen
// port on the wan, then default-deny on the VPN interface with one explicit
// pass per client/service grant. Default deny means a client with no grants
// reaches nothing on the network.
func wgServerRules(b *strings.Builder, cfg config.Config, wan config.Interface) {
	s := cfg.WireGuard.Server
	if !cfg.WireGuard.Enabled || !s.Enabled {
		return
	}
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	keepState := "keep state"
	if cfg.Flow.Enabled {
		keepState = "keep state (pflow)"
	}

	w("# WireGuard remote-access server")
	w("pass in on $%s inet proto udp from any to ($%s) port %d %s", macro(wan), macro(wan), s.Port(), keepState)
	// Default deny on the VPN interface; every grant below is an explicit allow.
	w("block in on %s all", WGServerDevice)
	// Name resolution is not a grantable service — it is infrastructure the
	// generated client configs already point at (render.WGClient sets DNS to
	// the LAN address). Without this the default deny above swallows every
	// client lookup and the VPN looks like it has no internet at all.
	if lan, ok := byRole(cfg, "lan"); ok && cfg.DNS.Enabled && lan.IPv4 != "" {
		if ip := strings.SplitN(lan.IPv4, "/", 2)[0]; ip != "" {
			w("pass in on %s inet proto { tcp udp } from any to %s port 53 %s # dns for vpn clients",
				WGServerDevice, ip, keepState)
		}
	}
	for _, c := range s.Clients {
		clientIP := strings.SplitN(c.Address, "/", 2)[0]
		for _, id := range c.ServiceIDs {
			svc, ok := cfg.Service(id)
			if !ok {
				continue
			}
			w("pass in on %s inet proto %s from %s to %s port %d %s # %s -> %s",
				WGServerDevice, proto(svc.Proto), clientIP, svc.IP, svc.Port, keepState, c.Email, svc.Name)
		}
	}
	w("")
}

// writeManagementRules emits the admin-plane policy: the WebUI and sshd are
// reachable only from the configured sources, and blocked from everywhere else
// on every interface.
//
// The block is `quick` and comes first so it wins over the segment passes
// below. Ordering it the other way round would let a trusted-segment pass
// admit management traffic before the block was ever consulted — the classic
// way a management ACL ends up decorative.
func writeManagementRules(b *strings.Builder, cfg config.Config, keepState string) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	ports := cfg.System.Management.ManagementPorts()
	if len(ports) == 0 {
		return
	}
	portList := pfPortList(ports)

	w("# Admin plane: the WebUI and sshd.")
	sources := cfg.System.Management.Sources
	if len(sources) == 0 {
		// Default: the LAN, which is what the appliance did before this policy
		// existed. Narrowing it on upgrade would risk locking an admin out of
		// their own firewall, which is worse than the exposure it closes.
		if lan, ok := byRole(cfg, "lan"); ok {
			w("# No explicit sources configured, so the whole LAN may manage the box.")
			w("pass in quick on $%s inet proto tcp from $%s:network to (self) port %s %s",
				macro(lan), macro(lan), portList, keepState)
		}
	} else {
		w("management_sources = \"{ %s }\"", strings.Join(sources, " "))
		// One pass per non-WAN interface, never a bare `pass in quick`.
		//
		// An interface-agnostic rule would mean a source list containing a
		// public prefix — a mistake, or a restored backup — opens the WebUI on
		// the WAN. The admin plane should not be reachable from the internet
		// whatever the list says, so the ruleset does not offer the option.
		for _, ifc := range cfg.Interfaces {
			if ifc.Role == "wan" {
				continue
			}
			w("pass in quick on $%s inet proto tcp from $management_sources to (self) port %s %s",
				macro(ifc), portList, keepState)
		}
	}
	// Everything else, on every interface including the ones passed as trusted
	// below.
	w("block in log quick inet proto tcp to (self) port %s", portList)
	w("")
}

// writeSegmentRules emits one block per non-WAN interface according to its
// trust level.
func writeSegmentRules(b *strings.Builder, cfg config.Config, keepState string) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }

	for _, ifc := range cfg.Interfaces {
		if ifc.Role == "wan" || (ifc.IPv4 == "" && !ifc.DHCPClient) {
			continue
		}
		switch ifc.TrustLevel() {
		case config.TrustTrusted:
			w("# %s (trusted): full access.", ifc.Name)
			w("pass in on $%s inet all %s", macro(ifc), keepState)

		case config.TrustGuest:
			// Appliance services, then the internet, then nothing else. The
			// order matters: the block is quick, so it must come after the
			// passes it is meant to leave alone.
			w("# %s (guest): appliance services and the internet, not the LAN.", ifc.Name)
			w("pass in quick on $%s inet proto { tcp udp } from $%s:network to (self) port { 53 67 123 } %s",
				macro(ifc), macro(ifc), keepState)
			w("pass in quick on $%s inet proto icmp from $%s:network to (self) icmp-type echoreq %s",
				macro(ifc), macro(ifc), keepState)
			writeNoLocalRule(w, cfg, ifc)
			w("pass in on $%s inet from $%s:network to any %s", macro(ifc), macro(ifc), keepState)

		case config.TrustIsolated:
			// DHCP only, because a host that cannot get a lease cannot use the
			// segment at all. Everything else on the box is closed, and hosts
			// on the segment cannot reach each other either.
			w("# %s (isolated): DHCP and the internet only.", ifc.Name)
			w("pass in quick on $%s inet proto udp from any to (self) port 67 %s", macro(ifc), keepState)
			w("block in quick on $%s inet from $%s:network to $%s:network",
				macro(ifc), macro(ifc), macro(ifc))
			writeNoLocalRule(w, cfg, ifc)
			w("pass in on $%s inet from $%s:network to any %s", macro(ifc), macro(ifc), keepState)
		}
		w("")
	}
}

// writeNoLocalRule blocks a segment from reaching the appliance itself and
// every other configured subnet, leaving only the route out.
//
// Naming the other subnets explicitly rather than relying on RFC1918 lists:
// the appliance knows exactly which networks it serves, and a hand-maintained
// private-address list is how a segment ends up with a hole in it the day
// someone renumbers.
func writeNoLocalRule(w func(string, ...any), cfg config.Config, from config.Interface) {
	var nets []string
	nets = append(nets, "(self)")
	for _, other := range cfg.Interfaces {
		if other.Name == from.Name || other.Role == "wan" {
			continue
		}
		if other.IPv4 == "" && !other.DHCPClient {
			continue
		}
		nets = append(nets, "$"+macro(other)+":network")
	}
	w("block in log quick on $%s inet from $%s:network to { %s }",
		macro(from), macro(from), strings.Join(nets, " "))
}

// pfPortList renders a port list for a pf rule: a bare number when there is
// one, a braced set otherwise.
func pfPortList(ports []int) string {
	if len(ports) == 1 {
		return strconv.Itoa(ports[0])
	}
	parts := make([]string, 0, len(ports))
	for _, p := range ports {
		parts = append(parts, strconv.Itoa(p))
	}
	return "{ " + strings.Join(parts, " ") + " }"
}

func byRole(cfg config.Config, role string) (config.Interface, bool) {
	for _, ifc := range cfg.Interfaces {
		if ifc.Role == role {
			return ifc, true
		}
	}
	return config.Interface{}, false
}

// macro derives the pf macro name from the interface name: WAN -> wan_if.
func macro(ifc config.Interface) string {
	name := strings.ToLower(ifc.Name)
	var b strings.Builder
	for _, r := range name {
		if r >= 'a' && r <= 'z' || r >= '0' && r <= '9' {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	return b.String() + "_if"
}

// proto maps the config proto to pf syntax; tcp/udp becomes a list.
func proto(p string) string {
	if p == "tcp/udp" {
		return "{ tcp udp }"
	}
	return p
}

// resolvedForward is a port forward with its destination resolved from the
// referenced service, so the rdr/pass renderers don't repeat the lookup.
type resolvedForward struct {
	Name     string
	Proto    string
	WANPort  int
	DestIP   string
	DestPort int
}

// enabledForwards returns the enabled port forwards with their service
// destinations resolved. Forwards whose service is missing are skipped;
// Validate guarantees the reference exists, so that only guards rendering of a
// transiently inconsistent config.
func enabledForwards(cfg config.Config) []resolvedForward {
	var out []resolvedForward
	for _, pf := range cfg.NAT.PortForwards {
		if !pf.Enabled {
			continue
		}
		svc, ok := cfg.Service(pf.ServiceID)
		if !ok {
			continue
		}
		out = append(out, resolvedForward{
			Name:     pf.Name,
			Proto:    svc.Proto,
			WANPort:  pf.WANPort,
			DestIP:   svc.IP,
			DestPort: svc.Port,
		})
	}
	return out
}

// wgTunnelDevices returns the interface name of each configured site-to-site
// tunnel. It must agree with render.WireGuard's file naming, which numbers
// tunnels wg0..wgN in config order — the tunnel's config file name is what
// wg-quick takes as the interface name.
func wgTunnelDevices(cfg config.Config) []string {
	if !cfg.WireGuard.Enabled {
		return nil
	}
	out := make([]string, 0, len(cfg.WireGuard.Tunnels))
	for i := range cfg.WireGuard.Tunnels {
		out = append(out, WGTunnelDevice(i))
	}
	return out
}

// wgListenPorts returns the listen ports of enabled WireGuard tunnels,
// deduplicated, in tunnel order.
func wgListenPorts(cfg config.Config) []int {
	if !cfg.WireGuard.Enabled {
		return nil
	}
	seen := map[int]bool{}
	var out []int
	for _, t := range cfg.WireGuard.Tunnels {
		if t.ListenPort > 0 && !seen[t.ListenPort] {
			seen[t.ListenPort] = true
			out = append(out, t.ListenPort)
		}
	}
	return out
}
