package render

import (
	"fmt"
	"strings"

	"firewall/ui/internal/config"
)

// Pflow renders the kernel pflow(4) exporter setup for the baseline visibility
// pipeline (plan.md §8, docs/visibility-design.md). pflow(4) ships the pf state
// table as IPFIX with zero userland packet copy; fwd's in-process collector
// (internal/flow) receives it on localhost and summarizes flows into SQLite for
// the native Flows view.
//
// Output is a FreeBSD rc.conf.d fragment that clones a pflow0 interface and
// points it at the collector. Export is localhost-only — the flow data never
// leaves the box — and uses pflowproto 10 (IPFIX), which the collector decodes.
//
// When Flow is disabled the fragment is comment-only; apply pairs it with an
// interface-destroy reload so nothing exports.
func Pflow(cfg config.Config) (string, error) {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# Generated by fwd — do not edit; changes are overwritten on apply.")
	w("# pflow(4) exports the pf state table as IPFIX to fwd's flow collector")
	w("# (docs/visibility-design.md). Localhost-only; pflowproto 10 = IPFIX.")
	if !cfg.Flow.Enabled {
		w("# Baseline network visibility is disabled.")
		return b.String(), nil
	}

	// flowsrc is only the address stamped on export packets; the collector
	// binds localhost, so localhost on both ends keeps the export on the box.
	port := cfg.Flow.CollectorPort()
	w(`cloned_interfaces="pflow0"`)
	w(`create_args_pflow0="pflowsrc 127.0.0.1 pflowdst 127.0.0.1:%d pflowproto 10"`, port)
	return b.String(), nil
}
