package render

import (
	"fmt"
	"strings"

	"firewall/ui/internal/config"
)

// PflowService is the rc.d service name and path for the generated pflow setup
// script. fwd renders the script here; apply enables and (re)starts it.
const (
	PflowService = "fwpflow"
	PflowRcPath  = "/usr/local/etc/rc.d/" + PflowService
)

// Pflow renders the rc.d script that configures the kernel pflow(4) exporter for
// the baseline visibility pipeline (plan.md §8, docs/visibility-design.md).
// pflow(4) ships the pf state table as IPFIX with zero userland packet copy;
// fwd's in-process collector (internal/flow) receives it on localhost.
//
// FreeBSD configures pflow through pflowctl(8) (new in 15.0), not an ifconfig
// clone: `pflowctl -c` creates an exporter, `pflowctl -s pflowN src/dst/proto`
// configures it. That is imperative, so it is wrapped in an rc.d service for
// boot persistence and so apply can (re)start it. The script is idempotent —
// it deletes any existing exporters before creating ours — so repeated applies
// don't stack exporters. pf must also flag states with `set state-defaults
// pflow` (render.PF) or nothing is exported.
//
// When Flow is disabled the script's start is a no-op (it only tears down);
// apply pairs it with a service stop so nothing exports.
func Pflow(cfg config.Config) (string, error) {
	port := cfg.Flow.CollectorPort()

	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("#!/bin/sh")
	w("# Generated by fwd — do not edit; changes are overwritten on apply.")
	w("# pflow(4) exporter setup for the baseline flow collector")
	w("# (docs/visibility-design.md). Configured via pflowctl(8); IPFIX = proto 10.")
	w("#")
	w("# PROVIDE: %s", PflowService)
	w("# REQUIRE: pf")
	w("# KEYWORD: nojail")
	w("")
	w(". /etc/rc.subr")
	w("")
	w("name=%s", PflowService)
	w("rcvar=%s_enable", PflowService)
	w("start_cmd=%s_start", PflowService)
	w("stop_cmd=%s_stop", PflowService)
	w("")
	w("load_rc_config $name")
	w(": ${%s_enable:=\"NO\"}", PflowService)
	w("")
	// Tear down every existing exporter so create is idempotent across applies.
	w("%s_clear() {", PflowService)
	w("\tfor id in $(pflowctl -l 2>/dev/null | awk -F: '/^pflow/{print $1}'); do")
	w("\t\tpflowctl -d \"$id\" 2>/dev/null")
	w("\tdone")
	w("}")
	w("")
	w("%s_start() {", PflowService)
	if cfg.Flow.Enabled {
		w("\tkldload -n pflow 2>/dev/null")
		w("\t%s_clear", PflowService)
		w("\tpflowctl -c")
		w("\tpflowctl -s pflow0 src 127.0.0.1 dst 127.0.0.1:%d proto 10", port)
		w("\techo 'pflow exporter -> 127.0.0.1:%d (IPFIX)'", port)
	} else {
		w("\t# Baseline network visibility is disabled.")
		w("\t%s_clear", PflowService)
	}
	w("}")
	w("")
	w("%s_stop() {", PflowService)
	w("\t%s_clear", PflowService)
	w("}")
	w("")
	w("run_rc_command \"$1\"")

	return b.String(), nil
}
