package render

import (
	"fmt"
	"net"
	"strings"

	"firewall/ui/internal/config"
)

// AdblockInclude is where the blocklist compiler writes its local-zone data;
// the fetch/compile job is separate from rendering (runtime, network-bound).
const AdblockInclude = "/var/db/fwd/adblock.conf"

// TLSCertBundle is the CA bundle unbound verifies DNS-over-TLS upstreams
// against, as installed by the FreeBSD ca_root_nss package.
const TLSCertBundle = "/usr/local/share/certs/ca-root-nss.crt"

// usesDoT reports whether any configured upstream is DNS-over-TLS. A hostname
// on an upstream is what turns TLS on (config.System.DNSServers).
func usesDoT(cfg config.Config) bool {
	for _, d := range cfg.System.DNSServers {
		if d.Hostname != "" {
			return true
		}
	}
	return false
}

// Unbound renders unbound.conf: a validating recursive resolver listening on
// the internal interfaces only, with local-data for the appliance itself and
// configured host overrides.
func Unbound(cfg config.Config) (string, error) {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	// Internal interfaces with addresses: listen + allow, and pin the
	// appliance's own name to the LAN address.
	type ifaceNet struct {
		ip  net.IP
		net *net.IPNet
	}
	var internal []ifaceNet
	for _, ifc := range cfg.Interfaces {
		if ifc.Role == "wan" || ifc.IPv4 == "" {
			continue
		}
		ip, ipnet, err := net.ParseCIDR(ifc.IPv4)
		if err != nil {
			return "", fmt.Errorf("unbound: %s address: %w", ifc.Name, err)
		}
		internal = append(internal, ifaceNet{ip, ipnet})
	}
	if len(internal) == 0 {
		return "", fmt.Errorf("unbound: no internal interface with a static address")
	}

	w("# Generated by fwd — do not edit; changes are overwritten on apply.")
	w("server:")
	w("    verbosity: 1")
	w("    do-ip6: no") // TODO: revisit with the IPv6 story (plan.md §12)
	w("    interface: 127.0.0.1")
	for _, in := range internal {
		w("    interface: %s", in.ip)
	}
	w("    access-control: 0.0.0.0/0 refuse")
	w("    access-control: 127.0.0.0/8 allow")
	for _, in := range internal {
		w("    access-control: %s allow", in.net)
	}
	// Remote-access clients are handed the appliance as their resolver
	// (render.WGClient writes DNS = the LAN address), but they arrive from
	// the tunnel subnet, which is not one of the interface networks above.
	// Without this every connected client's name resolution is refused and
	// the split-tunnel config looks simply broken.
	if vpn, ok := wgServerNet(cfg); ok {
		w("    access-control: %s allow", vpn)
	}
	w("")
	w("    hide-identity: yes")
	w("    hide-version: yes")
	if usesDoT(cfg) {
		// Required for DNS-over-TLS: without a bundle unbound cannot verify
		// the upstream certificate. Installed by the ca_root_nss package,
		// which the appliance provisioning pulls in for this reason.
		w("    tls-cert-bundle: %s", TLSCertBundle)
	}
	w("    harden-glue: yes")
	w("    harden-dnssec-stripped: yes")
	w("    prefetch: yes")
	w("    # Never forward queries for private space upstream")
	w("    private-address: 10.0.0.0/8")
	w("    private-address: 172.16.0.0/12")
	w("    private-address: 192.168.0.0/16")
	w("")

	domain := cfg.System.Domain
	w("    local-zone: \"%s.\" transparent", domain)
	w("    local-data: \"%s.%s. IN A %s\"", cfg.System.Hostname, domain, internal[0].ip)
	for _, o := range cfg.DNS.Overrides {
		w("    local-data: \"%s. IN A %s\"", o.Host, o.IP)
		w("    local-data-ptr: \"%s %s.\"", o.IP, o.Host)
	}
	w("")

	if cfg.DNS.Adblock.Enabled {
		w("    # Compiled adblock blocklists (see AdblockInclude)")
		w("    include: %s", AdblockInclude)
		w("")
	}

	// Upstream forwarding. With no configured upstreams unbound stays a full
	// recursive resolver, which is the privacy-preserving default; configuring
	// upstreams is an explicit choice to trust (and be seen by) someone else.
	if len(cfg.System.DNSServers) > 0 {
		tls := usesDoT(cfg)
		w("forward-zone:")
		w("    name: \".\"")
		if tls {
			w("    forward-tls-upstream: yes")
		}
		for _, d := range cfg.System.DNSServers {
			if tls {
				// host@port#name: the name is what the certificate is
				// verified against, which is the whole point of DoT.
				w("    forward-addr: %s@853#%s", d.Address, d.Hostname)
			} else {
				w("    forward-addr: %s", d.Address)
			}
		}
	}

	return b.String(), nil
}

// wgServerNet returns the remote-access server's tunnel subnet, or ok=false
// when the server is off or its address is unusable.
func wgServerNet(cfg config.Config) (*net.IPNet, bool) {
	s := cfg.WireGuard.Server
	if !cfg.WireGuard.Enabled || !s.Enabled || s.Address == "" {
		return nil, false
	}
	_, n, err := net.ParseCIDR(s.Address)
	if err != nil {
		return nil, false
	}
	return n, true
}
