package render

import (
	"fmt"
	"net"
	"strings"

	"firewall/ui/internal/config"
)

// AdblockInclude is where the blocklist compiler writes its local-zone data;
// the fetch/compile job is separate from rendering (runtime, network-bound).
const AdblockInclude = "/var/db/fwd/adblock.conf"

// Unbound renders unbound.conf: a validating recursive resolver listening on
// the internal interfaces only, with local-data for the appliance itself and
// configured host overrides.
func Unbound(cfg config.Config) (string, error) {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	// Internal interfaces with addresses: listen + allow, and pin the
	// appliance's own name to the LAN address.
	type ifaceNet struct {
		ip  net.IP
		net *net.IPNet
	}
	var internal []ifaceNet
	for _, ifc := range cfg.Interfaces {
		if ifc.Role == "wan" || ifc.IPv4 == "" {
			continue
		}
		ip, ipnet, err := net.ParseCIDR(ifc.IPv4)
		if err != nil {
			return "", fmt.Errorf("unbound: %s address: %w", ifc.Name, err)
		}
		internal = append(internal, ifaceNet{ip, ipnet})
	}
	if len(internal) == 0 {
		return "", fmt.Errorf("unbound: no internal interface with a static address")
	}

	w("# Generated by fwd — do not edit; changes are overwritten on apply.")
	w("server:")
	w("    verbosity: 1")
	w("    do-ip6: no") // TODO: revisit with the IPv6 story (plan.md §12)
	w("    interface: 127.0.0.1")
	for _, in := range internal {
		w("    interface: %s", in.ip)
	}
	w("    access-control: 0.0.0.0/0 refuse")
	w("    access-control: 127.0.0.0/8 allow")
	for _, in := range internal {
		w("    access-control: %s allow", in.net)
	}
	w("")
	w("    hide-identity: yes")
	w("    hide-version: yes")
	w("    harden-glue: yes")
	w("    harden-dnssec-stripped: yes")
	w("    prefetch: yes")
	w("    # Never forward queries for private space upstream")
	w("    private-address: 10.0.0.0/8")
	w("    private-address: 172.16.0.0/12")
	w("    private-address: 192.168.0.0/16")
	w("")

	domain := cfg.System.Domain
	w("    local-zone: \"%s.\" transparent", domain)
	w("    local-data: \"%s.%s. IN A %s\"", cfg.System.Hostname, domain, internal[0].ip)
	for _, o := range cfg.DNS.Overrides {
		w("    local-data: \"%s. IN A %s\"", o.Host, o.IP)
		w("    local-data-ptr: \"%s %s.\"", o.IP, o.Host)
	}
	w("")

	if cfg.DNS.Adblock.Enabled {
		w("    # Compiled adblock blocklists (see AdblockInclude)")
		w("    include: %s", AdblockInclude)
	}

	return b.String(), nil
}
