package render

import (
	"fmt"
	"strings"

	"firewall/ui/internal/config"
)

// WGServerDevice is the fixed interface name for the remote-access server. It
// is deliberately independent of the wg0..wgN tunnel numbering so pf rules that
// reference the server interface stay stable as tunnels are added or removed.
const WGServerDevice = "wgsrv"

// WGFile is one rendered tunnel config, wg-quick format, consumed by the
// wireguard-tools rc.d script on FreeBSD (/usr/local/etc/wireguard/<name>).
type WGFile struct {
	Name    string // e.g. wg0.conf
	Content string
}

// WireGuard renders one wg-quick config per tunnel. Devices are numbered
// wg0..wgN in tunnel order.
// TODO: deleting a tunnel renumbers later devices; harmless for config files
// but revisit if anything starts referencing devices by name (pf rules on
// tunnel interfaces will).
func WireGuard(cfg config.Config) ([]WGFile, error) {
	var out []WGFile
	for i, t := range cfg.WireGuard.Tunnels {
		var b strings.Builder
		w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

		w("# Generated by fwd — do not edit; changes are overwritten on apply.")
		w("# Tunnel: %s", t.Name)
		w("[Interface]")
		w("Address = %s", t.Address)
		w("ListenPort = %d", t.ListenPort)
		w("PrivateKey = %s", t.PrivateKey)

		for _, p := range t.Peers {
			w("")
			w("# Peer: %s", p.Name)
			w("[Peer]")
			w("PublicKey = %s", p.PublicKey)
			w("AllowedIPs = %s", p.AllowedIPs)
			if p.Endpoint != "" {
				w("Endpoint = %s", p.Endpoint)
			}
			if p.Keepalive > 0 {
				w("PersistentKeepalive = %d", p.Keepalive)
			}
		}

		out = append(out, WGFile{
			Name:    fmt.Sprintf("wg%d.conf", i),
			Content: b.String(),
		})
	}
	if srv := wgServerFile(cfg); srv != nil {
		out = append(out, *srv)
	}
	return out, nil
}

// wgServerFile renders the remote-access server's wg-quick config, or nil when
// the server is off. Clients are [Peer] blocks; access control is enforced in
// pf, not here, so AllowedIPs is just each client's tunnel /32.
func wgServerFile(cfg config.Config) *WGFile {
	s := cfg.WireGuard.Server
	if !cfg.WireGuard.Enabled || !s.Enabled {
		return nil
	}
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# Generated by fwd — do not edit; changes are overwritten on apply.")
	w("# Remote-access server: %s", WGServerDevice)
	w("[Interface]")
	w("Address = %s", s.Address)
	w("ListenPort = %d", s.Port())
	w("PrivateKey = %s", s.PrivateKey)

	for _, c := range s.Clients {
		w("")
		w("# Client: %s", c.Email)
		w("[Peer]")
		w("PublicKey = %s", c.PublicKey)
		w("AllowedIPs = %s", c.Address)
	}
	return &WGFile{Name: WGServerDevice + ".conf", Content: b.String()}
}
