package render

import (
	"fmt"
	"strings"

	"firewall/ui/internal/config"
)

// WGFile is one rendered tunnel config, wg-quick format, consumed by the
// wireguard-tools rc.d script on FreeBSD (/usr/local/etc/wireguard/<name>).
type WGFile struct {
	Name    string // e.g. wg0.conf
	Content string
}

// WireGuard renders one wg-quick config per tunnel. Devices are numbered
// wg0..wgN in tunnel order.
// TODO: deleting a tunnel renumbers later devices; harmless for config files
// but revisit if anything starts referencing devices by name (pf rules on
// tunnel interfaces will).
func WireGuard(cfg config.Config) ([]WGFile, error) {
	var out []WGFile
	for i, t := range cfg.WireGuard.Tunnels {
		var b strings.Builder
		w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

		w("# Generated by fwd — do not edit; changes are overwritten on apply.")
		w("# Tunnel: %s", t.Name)
		w("[Interface]")
		w("Address = %s", t.Address)
		w("ListenPort = %d", t.ListenPort)
		w("PrivateKey = %s", t.PrivateKey)

		for _, p := range t.Peers {
			w("")
			w("# Peer: %s", p.Name)
			w("[Peer]")
			w("PublicKey = %s", p.PublicKey)
			w("AllowedIPs = %s", p.AllowedIPs)
			if p.Endpoint != "" {
				w("Endpoint = %s", p.Endpoint)
			}
			if p.Keepalive > 0 {
				w("PersistentKeepalive = %d", p.Keepalive)
			}
		}

		out = append(out, WGFile{
			Name:    fmt.Sprintf("wg%d.conf", i),
			Content: b.String(),
		})
	}
	return out, nil
}
